Add support for HTML output.
sxtxixtxcxh/validate-on-save.tmbundle pull request #29
Opened 2017-03-20 19:39 UTC by MikeMcQuaid

Add support for commands to produce HTML output. Currently this just has been implemented for RuboCop, JSONLint and Shellcheck.

Not sure how to make this conditional on the Validate commands or if that’s even possible?

Let me know what you think about this and whether it makes more sense to fork the project instead. Personally I find the HTML output window to be a far superior method of using this bundle.

2017-03-28 19:44 UTC, MikeMcQuaid commented
@sxtxixtxcxh @claylo Any thoughts on this and whether it's better as a full fork? Thanks!

2017-03-28 20:07 UTC, sxtxixtxcxh requested changes
i think this will work out fine, but i don't have textmate to try it.

(might be time to pass the torch...)

2017-03-28 20:07 UTC, sxtxixtxcxh commented on Support/lib/validate_on_save/validators/ruby.rb
> +      result = VOS.htmlify_results(result, filepath)
maybe delete the  `return result unless VOS.opt("VOS_HTML")` from the `htmlify_results` method to the validation (RuboCop, JSONLint and Shellcheck) files, like:
```
      result = VOS.htmlify_results(result, filepath) if VOS.opt("VOS_HTML")
```

2017-03-28 20:07 UTC, sxtxixtxcxh commented on README.md
> +  * `VOS_HTML`: Display the validation result in the TextMate HTML output (defaults to "false")
can you mention which languages this will work for?

2017-03-28 20:10 UTC, claylo commented
@sxtxixtxcxh I can take the repo altogether if you like. :)

@MikeMcQuaid I'd really like to see this sort of thing evolve into a base for validators of many stripes, similar to how they've pulled it together on Atom. Thoughts on that?

2017-03-28 20:13 UTC, sxtxixtxcxh commented
might also consider using individual `VOS_RUBOCOP_HTML` flags...

2017-03-30 18:00 UTC, MikeMcQuaid commented on README.md
> +  * `VOS_HTML`: Display the validation result in the TextMate HTML output (defaults to "false")
Sure.

2017-03-30 18:02 UTC, MikeMcQuaid commented
> @sxtxixtxcxh I can take the repo altogether if you like. :)

Also happy to maintain this as I maintain one of the official bundles and use TextMate daily.

> Not sure how to make this conditional on the Validate commands or if that’s even possible?

This is the main blocker issue as far as I can see. @claylo, any thoughts on that? Basically there doesn't seem to be an easy way to configure from Rubyland whether the output goes to a tooltip or HTML box.

> I'd really like to see this sort of thing evolve into a base for validators of many stripes, similar to how they've pulled it together on Atom. Thoughts on that?

I'm open to that. Are you thinking in this repository or elsewhere?

2017-03-30 18:03 UTC, MikeMcQuaid commented
> how they've pulled it together on Atom. Thoughts on that?

In general I'm still stubbornly using TextMate despite everyone I know going to Atom so am open for doing any of these niceties. Don't look at my employer too closely 😉

2017-04-03 06:47 UTC, claylo commented
> In general I'm still stubbornly using TextMate despite everyone I know going to Atom so am open for doing any of these niceties. Don't look at my employer too closely

Hah! Yeah, I just can't get behind the Sublime and Atom approaches. As impressive as both are, they're just too damn slow.

> Also happy to maintain this as I maintain one of the official bundles and use TextMate daily.

I can't argue with that. I have many TextMate related goals on my project list, so if you're interested in taking the reins on this, it sounds like you're in a better spot to make it happen anyway. (What's really funny: one of my TextMate goals is making community TextMate bundles installable/updatable with Homebrew.)

> Basically there doesn't seem to be an easy way to configure from Rubyland whether the output goes to a tooltip or HTML box

I think I have to agree with that statement. The output is defined in the plist for the command, so I don't know what would happen if you called the `web_preview.rb` interface even if it were set to tooltip, or even "discard."

I started hunting around in the textmate/textmate repo to see if anything jumped out as tweakable from a script (didn't find anything on that), and in the process I saw the 24-day old inclusion of SyntaxMate. https://github.com/textmate/textmate/tree/master/Applications/SyntaxMate

So ... it's possible that others are on this same path, and we may want to see what those plans are before we go further down this road.

2017-04-03 06:56 UTC, MikeMcQuaid commented
> I can't argue with that. I have many TextMate related goals on my project list, so if you're interested in taking the reins on this, it sounds like you're in a better spot to make it happen anyway.

🆒 👍 

I'd suggest to @sxtxixtxcxh that giving us both commit rights might put this project in good hands?

> (What's really funny: one of my TextMate goals is making community TextMate bundles installable/updatable with Homebrew.)

Nice! I'd suggest installing them into the default Homebrew prefix and having a helper command which will do the symlinking after installation into a place TextMate wants to look. These could both live in the same custom tap.

> I think I have to agree with that statement. The output is defined in the plist for the command, so I don't know what would happen if you called the web_preview.rb interface even if it were set to tooltip, or even "discard."

The only thing I can think is that the shortcuts for one of the paths live in a separate repository (at which point it's debatable how much use having all this code be a single repository is).

> I started hunting around in the textmate/textmate repo to see if anything jumped out as tweakable from a script (didn't find anything on that), and in the process I saw the 24-day old inclusion of SyntaxMate. https://github.com/textmate/textmate/tree/master/Applications/SyntaxMate
> 
> So ... it's possible that others are on this same path, and we may want to see what those plans are before we go further down this road.

It looks like that's an RPC service for TextMate providing syntax highlighting to other applications so doesn't seem directly relevant to us.

2017-05-31 15:33 UTC, MikeMcQuaid commented
I've made my own dedicated Linting bundle for this stuff instead. Let me know what you think! https://github.com/MikeMcQuaid/Linter.tmbundle

2017-05-31 15:33 UTC, closed without merging